<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Analise_de_Algoritmos_T1</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="NUnit.Analyzers" Version="4.12.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter" Version="3.9.0" />
		<PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="AlgoritmosDotNet">
	    <HintPath>..\..\..\..\Downloads\AlgoritmosDotNet_v2.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
